### ISSUE TITLE
Metrics tab errors if not connected to the gateway node

### ISSUE THREAD

**Issue by pgarrison** [libremesh/lime-app#112]
This issue should be renamed: it happens when you *are* on the gateway node. We have 3 routers set up with the latest (according to Nico) version of LiMe, using Chromium 64. I'm connected to the node called school, which is the internet gateway. 
![Screenshot here](https://user-images.githubusercontent.com/5379348/36068315-7891f864-0ea0-11e8-80d5-2b91ed969e66.png)

**Comment by gmarcos87** [comment]
Nice catch! I've never tried the app on a gateway before, I'm always 4 or 5 jumps away. I'll figure it out soon. Instead of "From School - To Internet" I could say "School is the gateway to Internet."

**Comment by gmarcos87** [comment]
Hi @pgarrison, Is this the expected behavior?
![captura de pantalla de 2019-03-06 06-23-44](https://user-images.githubusercontent.com/10773838/53870183-79c5c200-3fd8-11e9-9c56-357555e91552.png)

**Comment by pgarrison** [comment]
You know better than I do : )
Seems reasonable!
