### ISSUE TITLE
LiMe app Config- unable to switch between access points

### ISSUE THREAD

**Issue by infrared0** [libremesh/lime-app#113]
I am on a Ubuntu 16.04 desktop with the latest version of the LiMe app running in Chrome. When I go to the Config tab and try to switch from one Libremesh access point to another, the following message appears, and I am not able to switch. The error message is also hard to understand for humans. The screenshot below shows the error message that shows before the app reloads and shows the Status page, but you can see that the access point has not switched.

![screenshot from 2018-02-10 17-35-21](https://user-images.githubusercontent.com/4676032/36068408-bd63779a-0e89-11e8-90f0-083ff7250a6c.png)

**Comment by gmarcos87** [comment]
Hello @infrared0 , maybe I need a little more context to understand why it didn't change node.
Beyond that, the message can be quite unhelpful, it just means you can't switch to that node because don't have the API installed.
What message do you think would be clearer?

**Comment by gmarcos87** [comment]
Hello @infrared0, the behavior was changing throughout the development. Currently if the app don't find an api in the selected node (for example http://gateway-node/ubus) redirects to the node where the client is connected (http://thisnode.info/ubus). Anyway I'm going to change the message to "This node is not compatible with LimeApp", is that OK for you?
