### ISSUE TITLE
Organizar Traducción

### ISSUE THREAD

**Issue by patogit** [libremesh/lime-app#116]
Vamos a hacer un branch aparte donde @translatewiki puede tener permisos de push directo, y propongo que se llama tw-translation. Creo que @gmarcos87 tendrá que organizar eso, siendo dueño del repo. ¿Cómo va la organización? ¿uhttpd sigue siendo el branch principal de desarrollo?

**Comment by gmarcos87** [comment]
The branch uhttpd is merged to develop, now that is the right one to incorporate changes. I understand that translatewiki would be in charge of keeping the new branch updated based on what we want?
If so, I can create the new branch.

**Comment by patogit** [comment]
I made https://github.com/translation-bridge/lime-app/tree/issue-119/i18n/translations
