### ISSUE TITLE
No se puede marcar ubicación usando Firefox o Chromium en la compu

### ISSUE THREAD

**Issue by patogit** [libremesh/lime-app#135]
Intento marcar la ubicación de un nodo, y aunque aparece el botón de "editar ubicación" nunca aparece el botón de "marcar como nueva ubicación" que aparece en Chrome en mi celular con Android 6.

**Comment by patogit** [comment]
rearranqué el router y ahora sí aparece el botón, pero no hace nada, igual como el issue https://github.com/libremesh/lime-app/issues/136

**Comment by patogit** [comment]
desapareció de nuevo el "marcar como ubicación nueva"

**Comment by gmarcos87** [comment]
Hola Pato, podes confirmar que esto sigue ocurriendo? En que hash de git estás haciendo el build de LimeApp
