### ISSUE TITLE
The url in the description does not work

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#141]
it says 404 on the css and javascript parts.

**Comment by Narutuffy** [comment]
Any update on this? @gmarcos87

**Comment by gmarcos87** [comment]
When you are developing you can change the parameter in preact.config.js to / then the build paths are made over the root of the url and not in /app. When the branch fbw-lime is merged the parameter can be changed with environment variables.
I consider this issue closed, and I will include it in the Readme.md.
