### ISSUE TITLE
In a device with only one 2.4 ghz radio, the align tool does not show any interface

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#143]
How to reproduce:
get one device with one 2.4ghz radio.
Build a lime_default image.
Access align page.

![screenshot from 2018-05-26 14-53-42](https://user-images.githubusercontent.com/1136597/40580099-ea05d17c-60f4-11e8-84d3-f26b91e3b092.png)

**Comment by gmarcos87** [comment]
This report corresponds to a previous version of the app and the problem is already solved in the current development branch.
