### ISSUE TITLE
create dummy app

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-app#148]
Hey, I'm eager to create some additional functionally to the lime-app but never touched these *web frameworks* before. Could you please create a *dummy app* which outputs some value received via `rpcd` and thereby shows the basic structure of a plugin?

Thank you very much

**Comment by aparcar** [comment]
@gmarcos87

**Comment by gmarcos87** [comment]
Hi @aparcar, I promise you that at some point I will write the tutorial, but for now I am over-assigned.
You can copy and modify the notes plugin, which is the simplest one the app has (https://github.com/libremesh/lime-app/tree/develop/plugins/lime-plugin-notes)

**Comment by aparcar** [comment]
@gmarcos87 take your time, I think the notes app is just fine for now! Thanks

**Comment by germanferrero** [comment]
Hey, we have done a step forward in this direction. Now there is a script to bootstrap a new plugin structure:
https://github.com/libremesh/lime-app/blob/develop/CONTRIBUTING.md#creating-a-new-plugin
