### ISSUE TITLE
Bug: all urls take you to rx page

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#162]
No matter which url you open the app with, it always takes you to #/rx

expected: if I type or click on a support link that takes me to http://thisnode.info/app/#/align, to see the alignment tool

what actually happens: redirects to http://thisnode.info/app/#/rx

**Comment by gmarcos87** [comment]
This feature can be easy to implement, it is simply necessary to set a path to redirect after logging into ubus.
