### ISSUE TITLE
Choose Interface language in first screen

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#167]
As a Indigenous User I need to be able to choose the interface language.

**Comment by germanferrero** [comment]
@nicopace wouldn't be enough with showing the interface in the browser language?

**Comment by nicopace** [comment]
Not always, as languages not always have a recognized language code

**Comment by germanferrero** [comment]
With the current i18n lib we can do this, if there is a community interested in adding support for their language, let's proceed by opening an issue for that specific case
