### ISSUE TITLE
in location page, name of connected node only appears after relocating it

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#198]
Expected behaviour: name of node to appear since page starts.
Actual behaviour: name only appear if I edit the node's location.

**Comment by nicopace** [comment]
it seems to be an intermitent issue, as it happened to me a couple of times but not now.

**Comment by germanferrero** [comment]
Closing this issue since the locate screen has been re-implemented.
In the new version the node name is not shown since it is always present in the header.
You can check how it looks [here](https://germanferrero.github.io/lime-app/?path=/story/containers-map--node-not-locatedcommunity-located)
