### ISSUE TITLE
Network check on background

### ISSUE THREAD

**Issue by gmarcos87** [libremesh/lime-app#20]

**Comment by gmarcos87** [comment]
Not posible in PWA and HTTP

**Comment by nicopace** [comment]
For this I would suggest an android native daemon :) small app that does this things

El 1 de agosto de 2017 12:30:23 AM GMT+02:00, Marcos Gutierrez <notifications@github.com> escribió:
>Not posible in PWA and HTTP
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libremesh/lime-app/issues/20#issuecomment-319214970

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
