### ISSUE TITLE
Duplicado Nombre de Nodo en la pantalla de Configuración

### ISSUE THREAD

**Issue by marcoarodriguez** [libremesh/lime-app#207]
Pasos para reproducir el error: 
1. EL día de hoy compilaron la bin, de libremesh usando el buildroot de librerouterorg.
2. Después de aplicar la configuración básica de nombre de red y nodo, funciono bien.
3. Ahora en el apartado de configuración del menú.

4. Esperaba encontrar en el ítem **Cambiar de nodo seleccionado** una sola opción, con el nombre del nodo que acabo de configurar y en su lugar encontré **el mismo nodo configurado repetido**.
![error-nodo-repetido](https://user-images.githubusercontent.com/55904852/65811017-e6243080-e177-11e9-913e-f108520f6ee0.png)

**Comment by gmarcos87** [comment]
Genial, era un bug conocido por mi pero estaba esperando que alguien reclame su solución para darle prioridad. Ahí estoy trabajando en el parche.

**Comment by nicopace** [comment]
Gracias @marcoarodriguez por reportar, y @gmarcos87 por cuidar la Lime-app :D
