### ISSUE TITLE
Validación de nombre de nodos y red

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#210]
En Firstbootwizard y la futura pantalla de settings de red/nodo, no aceptar nombres de nodo ni de red con caracteres inválidos (chequear Valid hostname)

**Comment by gmarcos87** [comment]
#212

**Comment by spiccinini** [comment]
This has been already implemented. 

I don't remember why we are forcing lowercase for the community name. Some communities that already use non lower case networks are having problems.

**Comment by ilario** [comment]
Some months ago I reported an issue about the force-to-lowercase function, you can find it here:
https://github.com/libremesh/lime-packages/issues/659

Basically I think that either we use a lowercase default network name or we do not force it to lowercase. Both options are perfectly fine for me. Just another thing: we should fix this decision before the next LibreMesh release and not change it anymore.

**Comment by spiccinini** [comment]
We should allow uppercase network names. Hostnames, in my opinion, in lowercase.  @germanferrero ?

**Comment by germanferrero** [comment]
Fixed at #268
