### ISSUE TITLE
Usage with BMX7

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-app#263]
would be nice to have this App running also with BMX7!

when i compare bmx6 and bmx7, f.i. some openwrt-packages were moved.
f.i. luci-app to https://github.com/openwrt/luci/tree/master/applications/luci-app-bmx7
there is a need for ubus-lime-bmx7, like https://github.com/libremesh/lime-packages/tree/master/packages/ubus-lime-bmx6

compared to bmx6, are there new values/parameters inside bmx7 which are important to see in the app? otherwise we could copy-paste a lot

**Comment by germanferrero** [comment]
Hi @FreifunkUFO, there is no functionality related to bmx (in any version) implemented in the limeapp. Also, bmx is not currently being used in libremesh either.
