### ISSUE TITLE
Install Error Ubuntu 18.04

### ISSUE THREAD

**Issue by rallep71** [libremesh/lime-app#273]
Hello,, 

install Error, what can i do?

linux@linuxasus:/media/Data/Libremesh/limeapp$ npm install 
npm WARN deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
loadDevDep:xhr-mock → 304 ▌ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine eslint-plugin-react-hooks@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDevDep:xhr-mock → 304 ▐ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:xhr-mock → net ▌ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-115-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

I have now updated nodejs and npm, 

my system ubuntu 18.04, kernel 4.15.0-115

nodejs -v v10.22.0
npm -v 6.14.6

linux@linuxasus:/media/Data/Libremesh/limeapp$ npm install
npm WARN @prefresh/webpack@0.8.2 requires a peer of preact@^10.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @storybook/preact@6.0.21 requires a peer of preact@^8.0.0|^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN leaflet.gridlayer.googlemutant@0.8.0 requires a peer of leaflet@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN preact-i18nline@2.0.0 requires a peer of preact@^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN preact-render-spy@1.3.0 requires a peer of preact@^8.1.0 but none is installed. You must install peer dependencies yourself.

audited 3715 packages in 41.349s

137 packages are looking for funding
  run `npm fund` for details

found 9 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by germanferrero** [comment]
installation is currently working on develop. I'm closing this, feel free to try it out yourself @rallep71 and let us know if that's not the case for you.
