### ISSUE TITLE
Community settings

### ISSUE THREAD

**Issue by nicoechaniz** [libremesh/lime-app#28]
When the app shows values such as signal level, throughput or packet loss, we differentiate acceptable values from bad values graphicaly (green vs. red). This acceptable values may vary for different communities and it should be possible to establish them in a config file.

suggested: /etc/config/lime-app

config lime-app
  option good_signal '-65'
  option bad_signal '-82'
  option good_bandwidth '5'  # measured in Mbps
  option bad_bandwidth '1'
  option acceptable_loss '20' # percentage

**Comment by gmarcos87** [comment]
#25
