### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#282]
The LiMe-app is a complex beast that is difficult to tame.
An extensive set of tools used (storybook, enzyme, husky, jest), react and its steep learning curve, all the architectural choices made (like plugins system, component lifecycle, lazy loading in some components), amongst multiple other things, make starting to work on the LiMe-app.

It would be good to have a developer guideline to help them bootstrap.

Some things that would potentially contribute could be:
1. Key architectural decisions, descriptions and designs: diagrams can help visualize the relationship between modules. one example would be state management using react query.
2. Coding preferences: ideally implemented in linters, but would be good if they are documented anyways. One example is react components as classes or functions.
3. How to approach when triaging a bug, when adding a new feature, etc.

**Comment by nicopace** [comment]
We can start with the [CONTRIBUTING.md](https://github.com/libremesh/lime-app/blob/develop/CONTRIBUTING.md) file.
It is good though it mostly focuses on the git workflow.

**Comment by germanferrero** [comment]
Hi @nicopace, I'm closing this since https://github.com/libremesh/lime-app/blob/develop/docs/Tutorial.md represents a bold step forward in this direction.
Let's open further issues addressing specific aspects of the documentation that could be missing.
