### ISSUE TITLE
Problem embedding https content inside the lime-app

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#290]
The new `remote support` feature embeds the console window within the lime-app window in an iframe, but as per the restrictions in the use of iframes, an http loaded website can't embed https content, so the page fails to load.
A cheap but not ideal solution would be to open it in a popup window (but the user would have left the lime-app screen).

Scratching my head on how to approach this :(

**Comment by ilario** [comment]
In the development page of the website we already propose a way to have https on the lime-app, if that is used there should be no problem, right?

**Comment by ilario** [comment]
I forgot to comment: we disabled the automatic redirect to httpS (see https://github.com/libremesh/lime-packages/pull/799), so either the user will have to specify httpS:// manually or a link including httpS protocol should be present in lime-app.

**Comment by nicopace** [comment]
Hi ilario... thanks for this... I assumed there was an issue, but there was actually not.
In an http site you can include https content, but not the other way around.
Closing this issue.
