### ISSUE TITLE
Align screen detail url grows

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-app#295]
The URL component  grows each time a node-detail view is displayed.

eg: http://10.186.0.1/app/#/aling-single/wlan1-mesh/aling-single/wlan1-mesh/aling-single/wlan1-mesh/aling-single/wlan1-mesh/aling-single/wlan1-mesh/aling-single/wlan1-mesh/aling-single/wlan1-mesh/A8:40:41:fe:ca:fe

**Comment by ilario** [comment]
"aling"?
