### ISSUE TITLE
App does not show up before switching to other tab and back

### ISSUE THREAD

**Issue by pony1k** [libremesh/lime-app#397]
When I open the app in a fresh browser tab, the page shows "Loading..." and does nothing, until I hit refresh, switch to another tab and back, minimize the browser window or something similiar. Here is a screenshot of the app with firefoxes network monitor, if that helps. The last 4 requests appeared just after switching back to the tab.
![Screenshot_20240123_204748](https://github.com/libremesh/lime-app/assets/84532040/bf475def-e4bf-438d-ba42-fc2e9beb78a1)
I'm using the current develop branch (5113561). This happens with firefox 121.0.1 as well as chromium 120.0.6099.224 (Official Build, ungoogled-chromium).

**Comment by selankon** [comment]
This will be fixed on https://github.com/libremesh/lime-app/pull/406
