### ISSUE TITLE
 uptime not refreshing

### ISSUE THREAD

**Issue by javierbrk** [libremesh/lime-app#425]
after pressing the update info button the uptime is not refreshing
at the moment of the data capture the uptime was "uptime": 2438.64, "hostname": "cheche", press f5 and it wont update, is it from the reference state ? Is there an error with my firmware ?

![image](https://github.com/libremesh/lime-app/assets/4826216/4c1e8823-5686-4b44-94c1-00a6b6ee340a)

**Comment by selankon** [comment]
This is not an error imo. 

The uptime is got from the reference state, so is normal that the refreshing time takes so long.

Anyway, if i click on the "update shared state button" (green button), and then click on the anywhere on the screen, the data is updated properly (the uptime too). 

Is this working for you?

**Comment by selankon** [comment]
Wait, I found that if a node is on the reference state happen exactly what you said, the uptime set is the reference state one. I fixed it on https://github.com/libremesh/lime-app/pull/422/commits/6056c5688ae09044f4cb1c79bd6454b5fc8733eb .

You still have to close/open the info data to see the updated data
