### ISSUE TITLE
Add board name on the main screen 

### ISSUE THREAD

**Issue by javierbrk** [libremesh/lime-app#436]
![imagen](https://github.com/user-attachments/assets/9661ba4c-2e8f-4521-a251-ab2acfc78c74)
It would be nice to have the board name in the main screen

**Comment by selankon** [comment]
Previous implementation was

![image](https://github.com/user-attachments/assets/9624b1ba-d0e5-4941-b192-d50cc23c2b7c)

**Comment by selankon** [comment]
A first iteration here 
![image](https://github.com/user-attachments/assets/65776bbb-0eaf-4c71-9659-f1bb97d066e9)
