### ISSUE TITLE
Improve the mesh upgrade "show nodes" button

### ISSUE THREAD

**Issue by javierbrk** [libremesh/lime-app#437]
It would be nice to move the "show nodes" or "ver nodos" button out of the green box or highlight it in some how 
![imagen](https://github.com/user-attachments/assets/cc307153-beb8-4fc3-8d96-f72d03271fb2)
It wold be nice to move the button out of the green box or highlight it in some how

**Comment by selankon** [comment]
Now it uses tabs:

![image](https://github.com/user-attachments/assets/27f2b25f-a447-47e8-b551-ba1ddd227237)
