### ISSUE TITLE
Change mtr by traceroute6

### ISSUE THREAD

**Issue by gmarcos87** [libremesh/lime-app#44]

**Comment by nicopace** [comment]
Why to do the change?

**Comment by gmarcos87** [comment]
This issue is actually in [lime-ui-ng] (https://github.com/libremesh/lime-ui-ng), by mistake I created it in this repository. @nicoechaniz

**Comment by gmarcos87** [comment]
This issue is actually in [lime-ui-ng](https://github.com/libremesh/lime-ui-ng), by mistake I created it in this repository. @nicoechaniz

**Comment by gmarcos87** [comment]
Fixed: libremesh/lime-ui-ng#bcb406b8511bb33a800145873fa5b17a3b28a8b3
