### ISSUE TITLE
Review the most active node selection

### ISSUE THREAD

**Issue by gmarcos87** [libremesh/lime-app#45]
The algorithm with which the most active link is obtained does not seem to coincide with what is observed or expected to be found. We were able to check it in our network, and the data obtained is wrong. In our network 'Cantor' shows 'Pablo' and should show 'Mario'

https://github.com/libremesh/lime-ui-ng/blob/master/lime-api-orange-rpc/files/usr/lib/orange/api/lime/api.lua#L363

**Comment by nicopace** [comment]
jeje... if you understand this it is ok... but for me it doesn't make sense at all jejeje

**Comment by gmarcos87** [comment]
This issue is actually in [lime-ui-ng] (https://github.com/libremesh/lime-ui-ng), by mistake I created it in this repository. @nicoechaniz
