### ISSUE TITLE
app crashes when node has no location at all

### ISSUE THREAD

**Issue by javierbrk** [libremesh/lime-app#451]
Default location is FIXME

![image](https://github.com/user-attachments/assets/ecbedef4-a32e-4210-a423-f2594ebc21a1)
and app cant handle it 
![Screenshot from 2024-09-09 16-25-23](https://github.com/user-attachments/assets/901fe0bd-0dbd-4315-ac9b-932e3ba208d0)

**Comment by javierbrk** [comment]
the problem seems to be when the fixme location propagates over all the data types

**Comment by selankon** [comment]
On which screen is this and what i have to do to reproduce it?

**Comment by selankon** [comment]
![image](https://github.com/user-attachments/assets/c9e3df3f-fae8-4e08-8a83-42ad7b190466)

Cannot reproduce it with a FIXME coords node

**Comment by selankon** [comment]
I finally reproduce it, this fixes the problem 8cf89e1
